
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  #- id: end-of-file-fixer
  #- id: trailing-whitespace
  #- id: check-json

# We use the Python version instead of the original version which seems to require Docker
# https://github.com/koalaman/shellcheck-precommit
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
    - id: shellcheck
      name: shellcheck
      args: ["--severity=error"]
      stages: [manual]

- repo: local
  hooks:
  - id: generate-index
    name: generate-index
    entry: python3 scripts/generate_index.py
    language: system
  - id: check-anchors
    name: check-anchors
    types: [markdown]
    entry: bash scripts/check_anchors/check-anchors.sh
    language: node
    
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17
  hooks:
    - id: mdformat
      args: ["--wrap=120", "--number"]
      additional_dependencies:
        [mdformat-gfm, mdformat-frontmatter, mdformat-footnote, mdformat-gfm-alerts]

- repo: https://github.com/tcort/markdown-link-check
  rev: v3.12.2
  hooks:
    - id: markdown-link-check
      args: ["-c", "markdown_link_config.json"]

- repo: https://github.com/rstcheck/rstcheck
  rev: v6.2.0
  hooks:
  - id: rstcheck
    additional_dependencies: [sphinx]
    args: ["--ignore-languages=c,python,java", "--report-level=error"]
    stages: [manual]

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.4
  hooks:
    - id: check-github-workflows

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: "v1.10.0"
  hooks:
    # - id: rst-backticks
    - id: rst-directive-colons
    - id: rst-inline-touching-normal

- repo: https://github.com/codespell-project/codespell
  rev: "v2.3.0"
  hooks:
  - id: codespell
    args: ["-L", "fle,re-use,merchantibility,synching,crate,nin,infinit,te,checkin"]
    exclude: |
            (?x)^(.*\.rst
            )$
