matrix:
  include:
    - name: "reStructuredText syntax check"
      dist: xenial
      language: python
      python:
        - 3.7
      install:
        - pip3 install rstcheck==3.3.1
      script:
        - rstcheck -r source/ --ignore-language c,python,java --report error

    - name: "JSON regeneration check"
      dist: xenial
      language: python
      python:
        - 3.7
      install:
        - npm install -g js-yaml
      script:
        - python3 ./source/server-discovery-and-monitoring/tests/errors/generate-error-tests.py
        - python3 ./source/client-side-encryption/etc/generate-corpus.py ./source/client-side-encryption/corpus
        - python3 ./source/client-side-encryption/etc/generate-test.py ./source/client-side-encryption/etc/test-templates/*.template ./source/client-side-encryption/tests
        - cd source && make && git diff --exit-code

    - name: "Unifed Test Format schema checks"
      dist: xenial
      language: python
      python:
        - 3.7
      install:
        - npm install -g ajv-cli
      script:
        - cd source/unified-test-format/tests && make
